"""sync models

Revision ID: 3e360f913355
Revises: 2249c2c1b373
Create Date: 2025-08-13 17:43:35.066411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e360f913355'
down_revision: Union[str, Sequence[str], None] = '2249c2c1b373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('slides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slide_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slide_extractions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slide_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slide_extractions_id'))

    op.drop_table('slide_extractions')
    # ### end Alembic commands ###
