"""initial users, judge0, submissions, slides

Revision ID: c4af184fbf4e
Revises: 
Create Date: 2025-08-15 00:17:35.741981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4af184fbf4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('slides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slide_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slide_extractions_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supabase_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='student', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_sign_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_supabase_id'), ['supabase_id'], unique=True)

    op.create_table('code_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('judge0_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_submissions_judge0_token'), ['judge0_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_code_submissions_user_id'), ['user_id'], unique=False)

    op.create_table('code_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('compile_output', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.String(length=50), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_results_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_results_submission_id'))

    op.drop_table('code_results')
    with op.batch_alter_table('code_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_code_submissions_judge0_token'))

    op.drop_table('code_submissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('slide_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slide_extractions_id'))

    op.drop_table('slide_extractions')
    # ### end Alembic commands ###
