"""judge0 models

Revision ID: ee5567bd1954
Revises: 
Create Date: 2025-08-12 02:29:57.536806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5567bd1954'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('judge0_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_submissions_judge0_token'), ['judge0_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_code_submissions_user_id'), ['user_id'], unique=False)

    op.create_table('code_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('compile_output', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.String(length=50), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_results_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_results_submission_id'))

    op.drop_table('code_results')
    with op.batch_alter_table('code_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_code_submissions_judge0_token'))

    op.drop_table('code_submissions')
    # ### end Alembic commands ###
