name: CI

on:
    push:
        branches: [dev, main]
    pull_request:

jobs:
    test_and_healthcheck:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Health check (server boots)
              env:
                  # CORS origins (origin only, no path)
                  ALLOW_ORIGINS: "https://recode-frontend.vercel.app"

                  # Optional — enable Auth in CI if you provide these
                  SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
                  SUPABASE_SERVICE_KEY: "${{ secrets.SUPABASE_SERVICE_KEY }}"

                  # Optional — only if your app expects a DB URL
                  # Prefer a dedicated DB secret; don't reuse SUPABASE_URL here.
                  DATABASE_URL: "${{ secrets.DATABASE_URL }}"

                  # General app env
                  APP_ENV: "ci"
                  PYTHONUNBUFFERED: "1"
              run: |
                  set -euo pipefail

                  # Start API
                  python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 --workers 1 &
                  UV_PID=$!
                  trap 'kill $UV_PID 2>/dev/null || true' EXIT

                  # Wait up to 15s for boot, fail if process dies
                  for i in {1..30}; do
                    if curl -fsS http://127.0.0.1:8000/healthz >/dev/null; then
                      echo "Server is up"
                      break
                    fi
                    if ! kill -0 "$UV_PID" 2>/dev/null; then
                      echo "Uvicorn exited early"
                      exit 1
                    fi
                    sleep 0.5
                  done

                  # Final assert
                  curl -fsS http://127.0.0.1:8000/healthz >/dev/null
