name: Labeler

on:
    pull_request_target:

permissions:
    contents: read
    pull-requests: write
    issues: write

jobs:
    label:
        runs-on: ubuntu-latest
        steps:
            - name: Apply labels from paths
              uses: actions/labeler@v5
              with:
                  configuration-path: .github/labeler.yml
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  sync-labels: true
